name: Build MetaCall Distributable

on:
  repository_dispatch:
    types: [test-trigger]
  pull_request:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Clean up previous dependencies in order to avoid conflicts with brew
      - name: Clean
        run: |
          brew uninstall --force --ignore-dependencies node
          brew cleanup -s node
          brew cleanup --prune-prefix
          brew uninstall --force --ignore-dependencies python@3.11
          brew cleanup -s python@3.11
          brew cleanup --prune-prefix
          brew uninstall --force --ignore-dependencies python@3.12
          brew cleanup -s python@3.12
          brew cleanup --prune-prefix
          sudo rm -rf /System/Library/Frameworks/Python.framework/
          brew cleanup --prune-prefix
          sudo rm -rf /usr/local/bin/2to3
          sudo rm -rf /usr/local/bin/2to3-3.11
          sudo rm -rf /usr/local/bin/2to3-3.12
          sudo rm -rf /usr/local/bin/idle3
          sudo rm -rf /usr/local/bin/idle3.11
          sudo rm -rf /usr/local/bin/idle3.12
          sudo rm -rf /usr/local/bin/pydoc3
          sudo rm -rf /usr/local/bin/pydoc3.11
          sudo rm -rf /usr/local/bin/pydoc3.12
          sudo rm -rf /usr/local/bin/python3
          sudo rm -rf /usr/local/bin/python3-config
          sudo rm -rf /usr/local/bin/python3.11
          sudo rm -rf /usr/local/bin/python3.12
          sudo rm -rf /usr/local/bin/python3.11-config
          sudo rm -rf /usr/local/bin/python3.12-config
          brew uninstall --force --ignore-dependencies ruby
          brew cleanup -s ruby
          brew cleanup --prune-prefix
          sudo rm -rf $(brew --repo homebrew/core)

      # Build Homebrew recipe
      - name: Build
        run:  ./build.sh

      # Release package
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          fail_on_unmatched_files: true
          files: pkg/*.pkg
